name: Keycloak Operator Kubernetes Resources Release

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
concurrency: keycloak-kubernetes-resources-release

env:
  JDK_VERSION: 11

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Calculate version
        id: version
        run: |
          echo "::set-output name=branch::${{github.ref_name}}"

          [ "${{github.ref_name}}" = "main" ] && \
            echo "::set-output name=version::latest" || \
            echo "::set-output name=version::${{github.ref_name}}"

      - name: Check version
        run: |
          echo "Branch: ${{steps.version.outputs.branch}}"
          echo "Version: ${{steps.version.outputs.version}}"

      - name: Update maven settings
        run: mkdir -p ~/.m2 ; cp .github/settings.xml ~/.m2/

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK_VERSION }}

      - name: Cache Maven packages
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: cache-1-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: cache-1-${{ runner.os }}-m2

      - name: Clone Keycloak
        run: |
          git clone --branch ${{steps.version.outputs.branch}} --depth 1 https://github.com/keycloak/keycloak.git

      - name: Build operator artifacts
        working-directory: keycloak
        run: |
          mvn -P operator -pl operator -am clean install -DskipTests \
              -Dquarkus.kubernetes.deployment-target=kubernetes,openshift,minikube

      - name: Create kubernetes resources
        run: |
          rm -rf ${{steps.version.outputs.version}}
          mkdir -p ${{steps.version.outputs.version}}/kubernetes

          cp -r keycloak/operator/target/kubernetes/*.yml ${{steps.version.outputs.version}}/kubernetes

      - name: Create OLM bundle
        run: |
          sudo snap install yq
          ./create-olm-bundle.sh ${{steps.version.outputs.version}} $(cat latest_version.txt)

      # TODO: automatic tagging on branches should be better checked
      # - name: Delete current tag
      #   run: |
      #     git tag -d ${{steps.version.outputs.version}} | true
      #     git push --delete origin ${{steps.version.outputs.version}} | true

      # - uses: stefanzweifel/git-auto-commit-action@master
      #   with:
      #     commit_message: Release resources for version ${{steps.version.outputs.version}}
      #     commit_options: '--no-verify --signoff'
      #     # branch: main
      #     # tagging_message: ${{steps.version.outputs.version}}
      #     disable_globbing: true
      #     push_options: '--force'
      #     # create_branch: true

      - name: Update the repository
        run: |
          git config --global user.email "andrea.peruffo1982@gmail.com"
          git config --global user.name "Andrea Peruffo"

          # Delete old tags
          git tag -d ${{steps.version.outputs.version}} | true
          git push --delete origin ${{steps.version.outputs.version}} | true

          # Update the main branch and tag it accordingly
          git add .
          git commit -m "Automatic update"
          git tag ${{steps.version.outputs.version}}
          git push origin HEAD:main --force
          git push origin ${{steps.version.outputs.version}}
